### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by kunihik0** [okada-lab/homepage_v2#11]
お疲れさまです．自分のページを更新してPush したところ
`ERROR: Permission to okada-lab/homepage_v2.git denied to kunihik0.`
`fatal: Could not read from remote repository.`
`Please make sure you have the correct access rights`

というエラーが出たので権限を確認していただいてもよろしいでしょうか？？

現状，岡田研ではないほかのgithubリポジトリでは問題なく行えているので，
僕のアカウント自体に問題は無いと思われます．
よろしくお願いいたします．

**Comment by motigome** [comment]
プルリクを送ってください。
